### ISSUE TITLE
TypeError: string indices must be integers, not str

### ISSUE THREAD

**Issue by seanauriti** [CoderBounty/coderbounty#138]
View details in Rollbar: [https://rollbar.com/coderbounty/Coderbounty/items/13/](https://rollbar.com/coderbounty/Coderbounty/items/13/)

```
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/website/views.py", line 62, in create_issue_and_bounty
    'title': issue_data['title'],
TypeError: string indices must be integers, not str
```

**Comment by seanauriti** [comment]
This was due to an error with github

**Comment by coderbounty-cowboy** [comment]
Coderbounty posted: http://coderbounty.com/issue/54
