### ISSUE TITLE
ImportError: No module named paypalrestsdk

### ISSUE THREAD

**Issue by seanauriti** [CoderBounty/coderbounty#159]
View details in Rollbar: [https://rollbar.com/coderbounty/Coderbounty/items/28/](https://rollbar.com/coderbounty/Coderbounty/items/28/)

```
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/website/views.py", line 129, in create_issue_and_bounty
    import paypalrestsdk
ImportError: No module named paypalrestsdk
```

**Comment by jose1937JS** [comment]
pip install paypalrestsdk==1.1.0
