### ISSUE TITLE
ProgrammingError: missing FROM-clause entry for table "google"
LINE 1: ... AND "website_issue"."language" = 'C#') ORDER BY ("www".goog...
                                                             ^


### ISSUE THREAD

**Issue by seanauriti** [CoderBounty/coderbounty#204]
View details in Rollbar: [https://rollbar.com/coderbounty/Coderbounty/items/47/](https://rollbar.com/coderbounty/Coderbounty/items/47/)

```
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/website/views.py", line 237, in list
    response = render_to_response('list.html', context, context_instance=RequestContext(request))
  File "/app/.heroku/python/lib/python2.7/site-packages/django/shortcuts.py", line 45, in render_to_response
    using=using)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/template/loader.py", line 114, in render_to_string
    template_name, context, context_instance, dirs, dictionary)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/template/engine.py", line 244, in render_to_string
    return t.render(context_instance)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/template/defaulttags.py", line 168, in render
    len_values = len(values)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/query.py", line 240, in __len__
    self._fetch_all()
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/query.py", line 1074, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/query.py", line 52, in __iter__
    results = compiler.execute_sql()
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 848, in execute_sql
    cursor.execute(sql, params)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: missing FROM-clause entry for table "google"
LINE 1: ... AND "website_issue"."language" = 'C#') ORDER BY ("www".goog...
                                                             ^

```

**Comment by seanauriti** [comment]
This is caused when unexpected values are inserted into the address query
