### ISSUE TITLE
DoesNotExist: Issue matching query does not exist.

### ISSUE THREAD

**Issue by seanauriti** [CoderBounty/coderbounty#223]
View details in Rollbar: [https://rollbar.com/coderbounty/Coderbounty/items/49/](https://rollbar.com/coderbounty/Coderbounty/items/49/)

```
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/website/views.py", line 570, in get_bounty_image
    issue = Issue.objects.get(id=id)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/query.py", line 387, in get
    self.model._meta.object_name
DoesNotExist: Issue matching query does not exist.
```

**Comment by seanauriti** [comment]
return a 404 if the issue does not exist.

**Comment by krtkmj** [comment]
@seanauriti I am working on this.
