### ISSUE TITLE
DoesNotExist: User matching query does not exist.

### ISSUE THREAD

**Issue by seanauriti** [CoderBounty/coderbounty#231]
View details in Rollbar: [https://rollbar.com/coderbounty/Coderbounty/items/50/](https://rollbar.com/coderbounty/Coderbounty/items/50/)

```
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/website/views.py", line 470, in get
    context = self.get_context_data(object=self.object)
  File "/app/website/views.py", line 561, in get_context_data
    comment_user = User.objects.get(username=comment.username)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/query.py", line 387, in get
    self.model._meta.object_name
DoesNotExist: User matching query does not exist.
```

**Comment by krtkmj** [comment]
@seanauriti cannot view in Rollbar, it says "Access not allowed".

**Comment by seanauriti** [comment]
comment_user = User.objects.get(username=comment.username) - it's because the github usernames are different from the coderbounty usernames.

**Comment by seanauriti** [comment]
I believe in the github API results, the avatar url is sent. https://developer.github.com/v3/issues/comments/
