### ISSUE TITLE
NameError: global name 'Sum' is not defined

### ISSUE THREAD

**Issue by seanauriti** [CoderBounty/coderbounty#309]
View details in Rollbar: [https://rollbar.com/coderbounty/Coderbounty/items/69/](https://rollbar.com/coderbounty/Coderbounty/items/69/)

```
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/views/generic/list.py", line 159, in get
    self.object_list = self.get_queryset()
  File "/app/website/views.py", line 368, in get_queryset
    "return User.objects.filter(payment__amount__gt=...total=Sum('payment__amount')).order_by('-total')"
NameError: global name 'Sum' is not defined
```

**Comment by Pal0r** [comment]
Sum is imported in line 34: `from django.db.models import Sum` in website.view.py. Close issue?

**Comment by seanauriti** [comment]
Thanks!
