### ISSUE TITLE
AttributeError: 'list' object has no attribute 'get'

### ISSUE THREAD

**Issue by seanauriti** [CoderBounty/coderbounty#311]
View details in Rollbar: [https://rollbar.com/coderbounty/Coderbounty/items/71/](https://rollbar.com/coderbounty/Coderbounty/items/71/)

```
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/website/views.py", line 443, in get
    txn_id=payout.items.get('transaction_id'),
AttributeError: 'list' object has no attribute 'get'
```

**Comment by farziengineer** [comment]
Hey @seanauriti Can you please tell how to reproduce this issue. When I go to the link, it shows me access not allowed error.
Thanks

**Comment by seanauriti** [comment]
this is when a payout is done.

**Comment by farziengineer** [comment]
Okay, will look into it.
